import { useState } from 'react';
import {
  discoverMemes,
  generateTagline,
  uploadFromUrl,
  type MemeCandidate,
  type MemeCategory,
  type Tagline,
  type UrlDownloadUpdate,
} from '../lib/api';
import type { ProbeResult } from '../types';

interface Props {
  onLoad: (probe: ProbeResult, candidate: MemeCandidate, tagline: Tagline | null) => void;
}

export function DiscoverPanel({ onLoad }: Props) {
  const [open, setOpen] = useState(false);
  const [candidates, setCandidates] = useState<MemeCandidate[]>([]);
  const [filter, setFilter] = useState<MemeCategory | ''>('');
  const [categories, setCategories] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [taglineConfigured, setTaglineConfigured] = useState(true);
  const [pickingUrl, setPickingUrl] = useState<string | null>(null);
  const [pickingMessage, setPickingMessage] = useState<string>('');

  async function fetchCandidates() {
    setLoading(true);
    setError(null);
    try {
      const result = await discoverMemes(filter || undefined);
      setCandidates(result.candidates);
      setCategories(result.categories);
      setTaglineConfigured(result.taglineConfigured);
      if (result.candidates.length === 0) {
        setError('No candidates returned. The source may be temporarily blocking us — try again in a minute.');
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setLoading(false);
    }
  }

  function expand() {
    setOpen(true);
    if (candidates.length === 0 && !loading) {
      fetchCandidates();
    }
  }

  async function pick(c: MemeCandidate) {
    setPickingUrl(c.url);
    setPickingMessage('Downloading…');
    setError(null);

    // Kick off download + tagline in parallel.
    const downloadPromise = uploadFromUrl(c.url, (u: UrlDownloadUpdate) => {
      if (u.message) setPickingMessage(u.message);
    });
    const taglinePromise = taglineConfigured
      ? generateTagline(c.title, c.category).catch((err) => {
          console.warn('tagline failed:', err);
          return null;
        })
      : Promise.resolve(null);

    try {
      const [probe, tagline] = await Promise.all([downloadPromise, taglinePromise]);
      onLoad(probe, c, tagline);
      setOpen(false);
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setPickingUrl(null);
      setPickingMessage('');
    }
  }

  if (!open) {
    return (
      <div className="discover-collapsed">
        <button className="discover-toggle" onClick={expand}>
          🔍 Discover memes
        </button>
      </div>
    );
  }

  return (
    <div className="discover-panel">
      <div className="discover-header">
        <h3>Discover memes</h3>
        <button className="link-btn" onClick={() => setOpen(false)}>
          Close
        </button>
      </div>

      <p className="muted" style={{ fontSize: '0.85em', margin: '4px 0 8px' }}>
        Auto-pulled from Reddit. Review and pick one — taglines are generated by AI.
      </p>

      <div className="discover-controls">
        <select
          value={filter}
          onChange={(e) => setFilter(e.target.value as MemeCategory | '')}
        >
          <option value="">All categories</option>
          {Object.entries(categories).map(([k, label]) => (
            <option key={k} value={k}>
              {label}
            </option>
          ))}
        </select>
        <button onClick={fetchCandidates} disabled={loading}>
          {loading ? 'Loading…' : 'Refresh'}
        </button>
      </div>

      {!taglineConfigured && (
        <p className="muted" style={{ fontSize: '0.8em', margin: '6px 0' }}>
          ⚠️ ANTHROPIC_API_KEY not set on the server — taglines will be blank.
          Add it to <code>server/.env</code> to enable.
        </p>
      )}

      {error && <p className="error" style={{ fontSize: '0.85em' }}>{error}</p>}

      <div className="discover-grid">
        {candidates.map((c) => {
          const isPicking = pickingUrl === c.url;
          return (
            <div key={c.url} className={`discover-card ${isPicking ? 'busy' : ''}`}>
              {c.thumbnailUrl ? (
                <img className="discover-thumb" src={c.thumbnailUrl} alt="" loading="lazy" />
              ) : (
                <div className="discover-thumb placeholder">▶</div>
              )}
              <div className="discover-meta">
                <div className="discover-title" title={c.title}>{c.title}</div>
                <div className="discover-sub">
                  {c.brandFit !== undefined && (
                    <span
                      className="discover-fit"
                      title="AI brand-fit score: how naturally this meme angles toward Luma Tech security messaging"
                    >
                      🎯 {c.brandFit}/10
                    </span>
                  )}
                  <span className="discover-cat">{categories[c.category] || c.category}</span>
                  <span className="discover-ups">↑ {c.upvotes.toLocaleString()}</span>
                  {c.durationSec !== null && (
                    <span className="discover-dur">{c.durationSec.toFixed(0)}s</span>
                  )}
                </div>
              </div>
              <button
                className="discover-pick"
                onClick={() => pick(c)}
                disabled={pickingUrl !== null}
              >
                {isPicking ? pickingMessage || 'Loading…' : 'Use this'}
              </button>
            </div>
          );
        })}
      </div>
    </div>
  );
}
